### ISSUE TITLE
Suggested Additions

### ISSUE THREAD

**Issue by Desae** [DeltaAnalytics/machine_learning_for_good#54]
**1. In module_1_introduction_pandas >> 1_1 intro_to_python:**
- In the section on Strings, I propose that other string methods should be taught (eg. find(), startswith() and join()).
- In the section on Lists, I propose that other list methods should be taught (eg. count(), sort() and copy()).
- In the section on DIctionaries, I propose that other dictionary methods should be taught (eg. keys(), values() and popitem()).
- In the section on Sets, I propose that other set methods should be taught (eg. add(), difference() and issubset()).
- I propose that a section is added on tuples.  

**2. In module_1_introduction_pandas >> 1_3_intro_to_pandas:**
- I propose that pd.info() method is introduced.
- Other pd.read_ methods like pd.read_excel(), pd.read_json() and pd.read_sql()  should be introduced apart from pd.read_csv().

**3. In module_1_introduction_pandas >> 1_5_exploratory_data_analysis:**
- In cell 7, num_df has not yet been defined and should be removed as it causes an error.

**Comment by CloudChaoszero** [comment]
Hello @Desae ,

Hope you are doing well! Thanks for checking out the Delta Analytics github repository! Means a lot for you to provide some critical feedback. I am one of the Teaching Fellows that recently came on, and happy to check this out.

**Comment by CloudChaoszero** [comment]
Hello! So for some of these requests, I added reference links to the documentation of each respective Jupyter Notebook, instead of providing examples. 

> I feel adding additional examples may disrupt the learning experience of goin through section 1 on Pandas, etc.

However, I will be fixing the `num_df` issue that you presented. Thanks so much for identifying that!
Here was the code that I re-arranged:
```
# Let's choose only a couple of columns to examine:
columns = ['loan_amount', 'funded_amount',  'status']
num_df = df[columns]
```
