### ISSUE TITLE
R_F_Suggestions

### ISSUE THREAD

**Issue by moreno61399** [DeltaAnalytics/machine_learning_for_good#62]
Hello all,

I have done some suggestions for Random Forest notebook.

1.  Added information: In random forest Heuristic is applied to select the best feature
2. I added df.head() that can be very helpfull for students to know which kind of data are they dealing with.
3. Also using describe() it is very interesting even more for a R_F Regressor to get some statistical information about our data
4. I suggest to add information in the beginning of the notebook about which kind of features do we have and their units
5. Improvements in the graphics could be done adding for example a reference line.

I hope this can help :)

**Comment by brianspiering** [comment]
Awesome!

**Comment by brianspiering** [comment]
Notebook has been updated. Closing this issue.
