### ISSUE TITLE
Data directory not found on module_4_classification

### ISSUE THREAD

**Issue by twiga2** [DeltaAnalytics/machine_learning_for_good#65]
On the notebook for section [4_1_logistic regression.ipynb](https://github.com/twiga2/machine_learning_for_good/blob/master/module_4_classification/4_1_logistic_regression.ipynb), the dataset 'admissions.csv' is missing. I couldn't locate the datasets directory

**Comment by brianspiering** [comment]
Good catch!

I'm switching over to use the standard Kiva Loans data
