### ISSUE TITLE
Module 9 (NLP PART 2): Stanford Resource link not found 

### ISSUE THREAD

**Issue by DimejiOladepo** [DeltaAnalytics/machine_learning_for_good#67]
Slides 65 and 66 in Module 9: Natural Language Processing Part 2 contains this link (http://web.stanford.edu/class/cs224u/materials/cs224u-2016-intro.pdf) which does not exist and I believe has been moved to https://web.stanford.edu/class/cs224u/2016/materials/cs224u-2016-intro.pdf

**Comment by brianspiering** [comment]
Thanks for pointing that out.

We'll update the link
